export const PATCHES = [
  `"#1 Worker"`,
  `Security Guard patch`,
  `Blood Type (Reference Patch)`,
  `Red Shirt Logo`,
  `"Don't Run, You'll Only Die Tired" Backpatch`,
  `Poker Hand: Dead Mans Hand*`,
  `Biohazard Symbol`,
  `Mr. Yuck`,
  `Nuclear Symbol`,
  `"Eat The Rich"`,
  `"Be Sure: Doubletap"`,
  `Flame Emoji`,
  `Smiley Face (Glow in the Dark)`,
  `"Smile: Big Brother is Watching"`,
  `Jolly Roger`,
  `Viking Skull`,
  `"APEX PREDATOR" (Sabertooth Skull)`,
  `Pin-Up Girl (Ace of Spades)`,
  `Queen of Hearts`,
  `Pin-Up Girl (Mechanic)`,
  `BOHICA`,
  `Front Towards Enemy (Claymore Mine)`,
  `Pin-Up Girl (Riding Missile)`,
  `FUBAR`,
  `"I'm A (Love) Machine"`,
  `Medic Patch (Skull and Crossbones on Logo)`,
  `HELLO MY NAME IS:`,
  `"Powered By Coffee"`,
  `"Take Me To Your Leader" (UFO)`,
  `"DO YOUR JOB"`,
  `"Take My Life (Please)"`,
  `"All Out of Fucks To Give" (Astronaut with Turned Out Pockets)`,
  `Allergic To Bullshit (Medical Style Patch)`,
  `"Fix Me First" (Caduceus)`,
  `"Upstanding Citizen"`,
  `NASA Logo`,
  `"Cowboy Up" (Crossed Revolvers)`,
  `Dove in Crosshairs`,
  `Chibi Cthulhu`,
  `"Welcome to the DANGER ZONE"`,
  `Skull and Crossed Wrenches`,
  `Pin-Up Girl (Succubus)`,
  `"DILLIGAF?"`,
  `"DRINK / FIGHT / FUCK"`,
  `"Work Hard / Party Harder"`,
  `Mudflap Girl`,
  `Fun Meter (reading: bad time)`,
  `"GAME OVER" (Bride & Groom)`,
  `Heart`,
  `"IMPROVE / ADAPT / OVERCOME"`,
  `"SUCK IT UP"`,
  `HMFIC`,
  `"Troubleshooter"`,
  `"IF I'M RUNNING KEEP UP" Backpatch`,
  `Crossed Hammers with Wings`,
  `"Keep Well Lubricated"`,
  `Soviet Hammer & Sickle`,
  `"Plays Well With Others"`,
  `"Live Free and Die"`,
  `Pin-Up Girl (Nurse): "The Louder You Scream the Faster I Come"`,
  `"Meat Bag"`,
  `"I Am Not A Robot"`,
  `Red Gear`,
  `"I Can't Fix Stupid"`,
  `"Space IS My Home" (Sad Astronaut)`,
  `All Seeing Eye`,
  `"Do I LOOK Like An Expert?"`,
  `"NOMAD"`,
  `"I'm Not A Rocket Scientist / But You're An Idiot"`,
  `"LONER"`,
  `"I Am My Brothers Keeper"`,
  `"Mama Tried"`,
  `Black Widow Spider`,
  `"My Other Ride Married You"`,
  `"One Size Fits All" (Grenade)`,
  `Grim Reaper Backpatch`,
  `("Get Fucked", in Russian)`,
  `"Smooth Operator"`,
  `Atom Symbol`,
  `"For Science!"`,
  `"Actually, I Am A Rocket Scientist"`,
  `"Help Wanted"`,
  `Princess`,
  `"I Like My Tools Clean / And My Women Dirty"`,
  `"GOOD BOY"`,
  `Dice (Snake Eyes)`,
  `"Travel To Distant Exotic Places / Meet Unusual Things / Get Eaten"`,
  `"Good" (Brain)`,
  `"Bad Bitch"`,
  `"Too Pretty To Die"`,
  `"Fuck Forever" (Roses)`,
  `Icarus`,
  `"Girls Best Friend" (Diamond)`,
  `Risk of Electrocution Symbol`,
  `Inverted Cross`,
  `"Do You Sign My Paychecks?" Backpatch`,
  `"I (heart) Myself"`,
  `Double Cherry`,
  `"Volunteer"`,
  `"Solve Et Coagula" (Baphomet)`,
];
