export const Trinkets = [
  `Preserved Insectile Aberration`,
  `Faded Green Poker Chip`,
  `Antique Company Script (Asteroid Mine)`,
  `Dessicated Husk Doll`,
  `Alien Pressed Flower (common)`,
  `Necklace of Shell Casings`,
  `Corroded Android Logic Core`,
  `Pamphlet: Signs of Parasitical Infection`,
  `Manual: Treat Your Rifle Like A Lady`,
  `Bone Knife`,
  `Calendar: Alien Pin-Up Art`,
  `Dog Tags (Heirloom)`,
  `Holographic Serpentine Dancer`,
  `Snake Whiskey`,
  `Medical Container, Purple Powder`,
  `Pills: Male Enhancement, Shoddy`,
  `Casino Playing Cards`,
  `Lagomorph Foot`,
  `Moonstone Ring`,
  `Manual: Mining Safety and You`,
  `Pamphlet: Against Human Simulacrum`,
  `Animal Skull, 3 Eyes, Curled Horns`,
  `Bartender's Certification (Expired)`,
  `Bent Wrench`,
  `Prospecting Mug, Dented`,
  `Eerie Mask`,
  `Vantablack Marble`,
  `Ivory Dice`,
  `Tarot Cards, Worn, Pyrite Gilded edges`,
  `Bag of Assorted Teeth`,
  `Ashes (A Relative)`,
  `DNR Beacon Necklace`,
  `Cigarettes (Grinning Skull)`,
  `Pills: Areca Nut`,
  `Rejected Application (Colony Ship)`,
  `Pamphlet: Android Overlords`,
  `Smut (Seditious): The Captain, Ordered`,
  `Key (Childhood Home)`,
  `Manual: Panic: Harbinger of Catastrophe`,
  `Token: "Is Your Morale Improving?"`,
  `Phosphorescent Sticks, Neon`,
  `Pamphlet: The Indifferent Stars`,
  `Calendar: Military Battles`,
  `Manual: Rich Captain, Poor Captain`,
  `Campaign Poster (Home Planet)`,
  `Pendant: Shell Fragments Suspended in Plastic`,
  `Titanium Toothpick`,
  `Gloves, Leather (Xenomorph Hide)`,
  `Pamphlet: Zen and the Art of Cargo Arrangement`,
  `Pictorial Pornography, Dogeared, Well Thumbed`,
  `Brass Knuckles`,
  `Fuzzy Handcuffs`,
  `Journal of Grudges`,
  `Stylized Cigarette Case`,
  `Ball of Assorted Gauge Wire`,
  `Spanner`,
  `Switchblade, Ornamental`,
  `Powdered Xenomorph Horn`,
  `Bonsai Tree`,
  `Golf Club (Putter)`,
  `Trilobite Fossil`,
  `Pamphlet: A Girl In Every Port`,
  `Patched Overalls, Personalized`,
  `Fleshy Thing Sealed in a Murky Jar`,
  `Spiked Bracelet`,
  `Harmonica`,
  `Manual: Spacefarer's Almanac (out of date)`,
  `Faded Photograph, A Windswept Heath`,
  `Stress Ball reads: Zero Stress in Zero G`,
  `Manual: Moonshining With Gun Oil & Fuel`,
  `Gyroscope, Bent, Tin`,
  `Coffee Cup, Chipped, HAPPINESS IS MANDATORY`,
  `Darts, Magnetic`,
  `Spray Paint`,
  `Wanted Poster, Weathered`,
  `Locket, Hair Braid`,
  `Pick, Miniature`,
  `Blanket, Fire Retardant`,
  `Hooded Parka, Fleece-Lined`,
  `BB Gun`,
  `Flint Hatchet`,
  `Pendant: Two Astronauts form a Skull`,
  `Rubik's Cube`,
  `Manual: Survival: Eat Soup With A Knife`,
  `Sputnik Pin`,
  `Ushanka`,
  `Trucker Cap, Mesh, Grey Alien Logo`,
  `Menthol Balm`,
  `Pith Helmet`,
  `10x10 Tarp`,
  `I Ching, Missing Sticks`,
  `Kukri`,
  `Trench Shovel`,
  `Shiv, Sharpened Butter Knife`,
  `Taxidermied Cat`,
  `Pamphlet: Interpreting Sheep Dreams`,
  `Pair of Shot Glasses, Spent Shotgun Shells`,
  `Opera Glasses`,
  `Pamphlet: The Relic of Flesh`,
  `Miniature Chess Set, Bone, Pieces Missing`,
];
